"""new database after lender renaming

Revision ID: 45badfc5e0fd
Revises: 
Create Date: 2022-02-01 21:20:40.415227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45badfc5e0fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('lender',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('content', sa.String(length=1000), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review_type', sa.String(length=50), nullable=True),
    sa.Column('loan_type', sa.String(length=50), nullable=True),
    sa.Column('date_posted', sa.String(length=30), nullable=True),
    sa.Column('author_name', sa.String(length=50), nullable=False),
    sa.Column('lender_name', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['author_name'], ['author.name'], ),
    sa.ForeignKeyConstraint(['lender_name'], ['lender.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review')
    op.drop_table('lender')
    op.drop_table('author')
    # ### end Alembic commands ###
