"""new db

Revision ID: fa485c72d3b2
Revises: 
Create Date: 2022-02-01 02:13:39.878758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa485c72d3b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('vendor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('content', sa.String(length=1000), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review_type', sa.String(length=50), nullable=True),
    sa.Column('loan_type', sa.String(length=50), nullable=True),
    sa.Column('author_name', sa.String(length=50), nullable=False),
    sa.Column('vendor_name', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['author_name'], ['author.name'], ),
    sa.ForeignKeyConstraint(['vendor_name'], ['vendor.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review')
    op.drop_table('vendor')
    op.drop_table('author')
    # ### end Alembic commands ###
